title: Amethyst Windows
google_analytics: G-LD9W6DQ801
show_downloads: true
github:
  appxbundle_url: https://github.com/glsorre/amethystwindows/releases/download/1.0.21122.1/AmethystWindowsPackaging_1.0.21126.12_x86_x64_ARM.appxbundle
  appxbundle_version: 1.0.21126.12
relative_links:
  enabled: true
  collections: true
include:
  - README.md
