title: Amethyst Windows v2
google_analytics: G-LD9W6DQ801
show_downloads: true
github:
  release_url: https://github.com/glsorre/amethystwindows/releases
relative_links:
  enabled: true
  collections: true
include:
  - README.md
