theme: jekyll-theme-slate
plugins:
  - jekyll-analytics
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
jekyll_analytics:
  GoogleAnalytics:
    id: UA-132556016-1
    anonymizeIp: true
include:
  - README.md
