title: Amethyst Windows
google_analytics: G-LD9W6DQ801
show_downloads: true
github:
  appxbundle_url: ms-appinstaller:?source=https://update.amethystwindows.com/AmethystWindowsPackaging.appinstaller
relative_links:
  enabled: true
  collections: true
include:
  - README.md
