theme: jekyll-theme-cayman
title: Amethyst Windows
google_analytics: G-LD9W6DQ801
show_downloads: true
github:
  appxbundle_url: https://github.com/glsorre/amethystwindows/releases/latest
relative_links:
  enabled: true
  collections: true
include:
  - README.md
