

version: 1.1.0.{build}

pull_requests:

  do_not_increment_build_number: true

configuration: Release

platform: x86

assembly_info:

  patch: true

  file: '**\AssemblyInfo.*'

  assembly_version: '{version}'

  assembly_file_version: '{version}'

  assembly_informational_version: '{version}'

build_script:

- ps: >-

    nuget restore





    [xml]$manifest= get-content "C:\projects\amethystwindows\AmethystWindows\Package.appxmanifest"



    $manifest.Package.Identity.Version = "$env:APPVEYOR_BUILD_VERSION"



    $manifest.save("C:\projects\amethystwindows\AmethystWindows\Package.appxmanifest")





    [xml]$manifest= get-content "C:\projects\amethystwindows\AmethystWindowsPackaging\Package.appxmanifest"



    $manifest.Package.Identity.Version = "$env:APPVEYOR_BUILD_VERSION"



    $manifest.save("C:\projects\amethystwindows\AmethystWindowsPackaging\Package.appxmanifest")





    msbuild "C:\projects\amethystwindows\AmethystWindows.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:GenerateAppInstallerFile=true /p:AppInstallerUri="https://update.amethystwindows.com" /p:AppInstallerUpdateFrequency=1 /p:AppInstallerCheckForUpdateFrequency=OnApplicationRun


    New-Item -ItemType Directory -Force -Path C:\projects\amethystwindows\AmethystWindowsPackaging\Binaries
    Copy-Item -Path "C:\projects\amethystwindows\AmethystWindowsSystray\bin" -Destination "C:\projects\amethystwindows\AmethystWindowsPackaging\Binaries\AmethystWindowsSystray" -Recurse
    Copy-Item -Path "C:\projects\amethystwindows\AmethystWindowsSystrayTests\bin" -Destination "C:\projects\amethystwindows\AmethystWindowsPackaging\Binaries\AmethystWindowsSystrayTests" -Recurse
    Copy-Item -Path "C:\projects\amethystwindows\AmethystWindowsWindows\bin" -Destination "C:\projects\amethystwindows\AmethystWindowsPackaging\Binaries\AmethystWindows" -Recurse

artifacts:

- path: AmethystWindowsPackaging\AppPackages

  name: AppPackages

- path: AmethystWindowsPackaging\Binaries

  name: Binaries

deploy:

- provider: Webhook

  url: https://app.signpath.io/API/v1/698a531d-4078-4f30-953b-6a9e9892e338/Integrations/AppVeyor?ProjectSlug=amethystwindows&SigningPolicySlug=test-signing

  authorization:

    secure: xCVRa1gtcPlfTZvZ2FA6890QXlY9SSPCdlUmcuwyEuzO7r1hjp0GpAn1UKe6E+xZW8y02VaNzPMXTv6sEeTIkw==

